version: "3.1"

networks:
  net:
    driver: bridge

services:
  notifications:
    image: notifications
    build: ./notifications/
    ports:
    depends_on:
      - kafka

  checkout:
    image: checkout
    build: ./checkout/
    ports:
      - "50051:50051"
    depends_on:
      - checkout-pgbouncer

  loms:
    image: loms
    build: ./loms/
    ports:
      - "50052:50052"
    depends_on:
      - loms-pgbouncer

  loms-db:
    image: postgres:15.1
    volumes:
      - loms_data:/var/lib/postgresql/loms_data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=loms
    container_name: "loms-db-container"

  loms-pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    ports:
      - 6432:6432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=loms
      - PGBOUNCER_DATABASE=loms
      - POSTGRESQL_HOST=loms-db
    depends_on:
      - loms-db

  checkout-db:
    image: postgres:15.1
    volumes:
      - checkout_data:/var/lib/postgresql/checkout_data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=checkout
    container_name: "checkout-db-container"

  checkout-pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    ports:
      - 6433:6433
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=checkout
      - PGBOUNCER_DATABASE=checkout
      - POSTGRESQL_HOST=checkout-db
      - PGBOUNCER_PORT=6433
    depends_on:
      - checkout-db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  loms_data:
  checkout_data:
  pg_data:
# notification:
#   image: notification
#   build: ./notification
#   ports:
#     - "8082:8082"
