version: "3.1"

services:
  checkout:
    image: checkout
    build: ./checkout/
    ports:
      - "50051:50051"
    depends_on:
      - checkout-pgbouncer

  loms:
    image: loms
    build: ./loms/
    ports:
      - "50052:50052"
    depends_on:
      - loms-pgbouncer

  loms-db:
    image: postgres:15.1
    volumes:
      - loms_data:/var/lib/postgresql/loms_data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=loms
    container_name: "loms-db-container"

  loms-pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    ports:
      - 6432:6432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=loms
      - PGBOUNCER_DATABASE=loms
      - POSTGRESQL_HOST=loms-db
    depends_on:
      - loms-db

  checkout-db:
    image: postgres:15.1
    volumes:
      - checkout_data:/var/lib/postgresql/checkout_data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=checkout
    container_name: "checkout-db-container"

  checkout-pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    ports:
      - 6433:6433
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=checkout
      - PGBOUNCER_DATABASE=checkout
      - POSTGRESQL_HOST=checkout-db
      - PGBOUNCER_PORT=6433
    depends_on:
      - checkout-db

volumes:
  loms_data:
  checkout_data:
  pg_data:
# notification:
#   image: notification
#   build: ./notification
#   ports:
#     - "8082:8082"
