// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock_loms_v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"

	loms "route256/loms/pkg/loms_v1"

	mock "github.com/stretchr/testify/mock"
)

// LomsV1Client is an autogenerated mock type for the LomsV1Client type
type LomsV1Client struct {
	mock.Mock
}

type LomsV1Client_Expecter struct {
	mock *mock.Mock
}

func (_m *LomsV1Client) EXPECT() *LomsV1Client_Expecter {
	return &LomsV1Client_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, in, opts
func (_m *LomsV1Client) CancelOrder(ctx context.Context, in *loms.CancelOrderRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *loms.CancelOrderRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *loms.CancelOrderRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *loms.CancelOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LomsV1Client_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type LomsV1Client_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *loms.CancelOrderRequest
//   - opts ...grpc.CallOption
func (_e *LomsV1Client_Expecter) CancelOrder(ctx interface{}, in interface{}, opts ...interface{}) *LomsV1Client_CancelOrder_Call {
	return &LomsV1Client_CancelOrder_Call{Call: _e.mock.On("CancelOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *LomsV1Client_CancelOrder_Call) Run(run func(ctx context.Context, in *loms.CancelOrderRequest, opts ...grpc.CallOption)) *LomsV1Client_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*loms.CancelOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *LomsV1Client_CancelOrder_Call) Return(_a0 *emptypb.Empty, _a1 error) *LomsV1Client_CancelOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LomsV1Client_CancelOrder_Call) RunAndReturn(run func(context.Context, *loms.CancelOrderRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *LomsV1Client_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, in, opts
func (_m *LomsV1Client) CreateOrder(ctx context.Context, in *loms.CreateOrderRequest, opts ...grpc.CallOption) (*loms.CreateOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *loms.CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *loms.CreateOrderRequest, ...grpc.CallOption) (*loms.CreateOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *loms.CreateOrderRequest, ...grpc.CallOption) *loms.CreateOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*loms.CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *loms.CreateOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LomsV1Client_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type LomsV1Client_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *loms.CreateOrderRequest
//   - opts ...grpc.CallOption
func (_e *LomsV1Client_Expecter) CreateOrder(ctx interface{}, in interface{}, opts ...interface{}) *LomsV1Client_CreateOrder_Call {
	return &LomsV1Client_CreateOrder_Call{Call: _e.mock.On("CreateOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *LomsV1Client_CreateOrder_Call) Run(run func(ctx context.Context, in *loms.CreateOrderRequest, opts ...grpc.CallOption)) *LomsV1Client_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*loms.CreateOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *LomsV1Client_CreateOrder_Call) Return(_a0 *loms.CreateOrderResponse, _a1 error) *LomsV1Client_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LomsV1Client_CreateOrder_Call) RunAndReturn(run func(context.Context, *loms.CreateOrderRequest, ...grpc.CallOption) (*loms.CreateOrderResponse, error)) *LomsV1Client_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrder provides a mock function with given fields: ctx, in, opts
func (_m *LomsV1Client) ListOrder(ctx context.Context, in *loms.ListOrderRequest, opts ...grpc.CallOption) (*loms.ListOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListOrder")
	}

	var r0 *loms.ListOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *loms.ListOrderRequest, ...grpc.CallOption) (*loms.ListOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *loms.ListOrderRequest, ...grpc.CallOption) *loms.ListOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*loms.ListOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *loms.ListOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LomsV1Client_ListOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrder'
type LomsV1Client_ListOrder_Call struct {
	*mock.Call
}

// ListOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *loms.ListOrderRequest
//   - opts ...grpc.CallOption
func (_e *LomsV1Client_Expecter) ListOrder(ctx interface{}, in interface{}, opts ...interface{}) *LomsV1Client_ListOrder_Call {
	return &LomsV1Client_ListOrder_Call{Call: _e.mock.On("ListOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *LomsV1Client_ListOrder_Call) Run(run func(ctx context.Context, in *loms.ListOrderRequest, opts ...grpc.CallOption)) *LomsV1Client_ListOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*loms.ListOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *LomsV1Client_ListOrder_Call) Return(_a0 *loms.ListOrderResponse, _a1 error) *LomsV1Client_ListOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LomsV1Client_ListOrder_Call) RunAndReturn(run func(context.Context, *loms.ListOrderRequest, ...grpc.CallOption) (*loms.ListOrderResponse, error)) *LomsV1Client_ListOrder_Call {
	_c.Call.Return(run)
	return _c
}

// OrderPayed provides a mock function with given fields: ctx, in, opts
func (_m *LomsV1Client) OrderPayed(ctx context.Context, in *loms.OrderPayedRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OrderPayed")
	}

	var r0 *emptypb.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *loms.OrderPayedRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *loms.OrderPayedRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *loms.OrderPayedRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LomsV1Client_OrderPayed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrderPayed'
type LomsV1Client_OrderPayed_Call struct {
	*mock.Call
}

// OrderPayed is a helper method to define mock.On call
//   - ctx context.Context
//   - in *loms.OrderPayedRequest
//   - opts ...grpc.CallOption
func (_e *LomsV1Client_Expecter) OrderPayed(ctx interface{}, in interface{}, opts ...interface{}) *LomsV1Client_OrderPayed_Call {
	return &LomsV1Client_OrderPayed_Call{Call: _e.mock.On("OrderPayed",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *LomsV1Client_OrderPayed_Call) Run(run func(ctx context.Context, in *loms.OrderPayedRequest, opts ...grpc.CallOption)) *LomsV1Client_OrderPayed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*loms.OrderPayedRequest), variadicArgs...)
	})
	return _c
}

func (_c *LomsV1Client_OrderPayed_Call) Return(_a0 *emptypb.Empty, _a1 error) *LomsV1Client_OrderPayed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LomsV1Client_OrderPayed_Call) RunAndReturn(run func(context.Context, *loms.OrderPayedRequest, ...grpc.CallOption) (*emptypb.Empty, error)) *LomsV1Client_OrderPayed_Call {
	_c.Call.Return(run)
	return _c
}

// Stocks provides a mock function with given fields: ctx, in, opts
func (_m *LomsV1Client) Stocks(ctx context.Context, in *loms.StocksRequest, opts ...grpc.CallOption) (*loms.StocksResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Stocks")
	}

	var r0 *loms.StocksResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *loms.StocksRequest, ...grpc.CallOption) (*loms.StocksResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *loms.StocksRequest, ...grpc.CallOption) *loms.StocksResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*loms.StocksResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *loms.StocksRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LomsV1Client_Stocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stocks'
type LomsV1Client_Stocks_Call struct {
	*mock.Call
}

// Stocks is a helper method to define mock.On call
//   - ctx context.Context
//   - in *loms.StocksRequest
//   - opts ...grpc.CallOption
func (_e *LomsV1Client_Expecter) Stocks(ctx interface{}, in interface{}, opts ...interface{}) *LomsV1Client_Stocks_Call {
	return &LomsV1Client_Stocks_Call{Call: _e.mock.On("Stocks",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *LomsV1Client_Stocks_Call) Run(run func(ctx context.Context, in *loms.StocksRequest, opts ...grpc.CallOption)) *LomsV1Client_Stocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*loms.StocksRequest), variadicArgs...)
	})
	return _c
}

func (_c *LomsV1Client_Stocks_Call) Return(_a0 *loms.StocksResponse, _a1 error) *LomsV1Client_Stocks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LomsV1Client_Stocks_Call) RunAndReturn(run func(context.Context, *loms.StocksRequest, ...grpc.CallOption) (*loms.StocksResponse, error)) *LomsV1Client_Stocks_Call {
	_c.Call.Return(run)
	return _c
}

// NewLomsV1Client creates a new instance of LomsV1Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLomsV1Client(t interface {
	mock.TestingT
	Cleanup(func())
}) *LomsV1Client {
	mock := &LomsV1Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
