-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS public.stocks
(
    warehouse_id bigint,
    sku bigint,
    count integer NOT NULL,
    CONSTRAINT stock_pk PRIMARY KEY (warehouse_id, sku)
);

CREATE TYPE order_status AS ENUM ('new', 'awaiting payment', 'failed', 'paid', 'cancelled');

CREATE TABLE IF NOT EXISTS public.orders (
    order_id BIGSERIAL PRIMARY KEY,
    user_id bigint NOT NULL,
    status order_status NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TYPE reserve_status AS ENUM ('new', 'paid');
CREATE TABLE IF NOT EXISTS public.stocks_reservation (
    order_id bigint,
    sku bigint,
    warehouse_id bigint,
    count integer NOT NULL,
    status reserve_status default 'new',
    CONSTRAINT stocks_reservation_pk PRIMARY KEY (order_id, sku, warehouse_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 1076963, 79) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 1076963, 99) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 1076963, 92) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 1076963, 50) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 1076963, 66) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 1076963, 26) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 1076963, 59) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 1148162, 25) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 1148162, 24) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 1148162, 57) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 1148162, 26) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 1148162, 18) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 1625903, 96) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 1625903, 12) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 1625903, 81) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 1625903, 68) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 1625903, 88) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 2956315, 18) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 2956315, 47) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 2956315, 27) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 2956315, 4) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 2956315, 11) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 2956315, 16) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 2956315, 67) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 2956315, 96) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 2958025, 45) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 2958025, 38) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 2958025, 36) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 2958025, 74) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 3596599, 55) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 3596599, 37) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 3596599, 74) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 3596599, 90) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 3618852, 26) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 3618852, 22) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 3618852, 35) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 3618852, 62) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 3618852, 88) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 3618852, 16) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 3618852, 99) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 4288068, 47) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 4288068, 85) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 4288068, 70) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 4288068, 84) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 4288068, 69) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 4288068, 4) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 4288068, 64) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 4288068, 90) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 4465995, 14) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 4465995, 74) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 4465995, 67) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 4465995, 83) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 4487693, 69) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 4669069, 10) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 4678816, 63) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 4687693, 7) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 4687693, 20) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 4687693, 4) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 4687693, 70) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 4687693, 39) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 4687693, 2) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 4687693, 20) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 5097510, 24) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 5647362, 22) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 5647362, 22) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 5647362, 9) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 5647362, 56) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 5647362, 6) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 6245113, 57) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 6245113, 0) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 6245113, 40) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 6245113, 31) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 6245113, 11) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 6245113, 32) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 6245113, 84) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 6245113, 51) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 6967749, 50) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 6967749, 22) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 6967749, 83) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 6967749, 98) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 6967749, 46) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 7277168, 90) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 7277168, 77) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 7277168, 71) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 7277168, 25) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 7277168, 32) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 7277168, 69) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 8748527, 15) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 8748527, 36) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 8748527, 48) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 8748527, 62) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 8748527, 75) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 8748527, 34) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 19045918, 61) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 19045918, 34) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 19045918, 8) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 19366373, 26) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 19366373, 38) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 19366373, 15) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 21435785, 33) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 21435785, 4) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 21435785, 83) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 21435785, 49) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 21435785, 50) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 24166967, 68) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 24167411, 97) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 24167411, 3) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 24167411, 28) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 24168225, 75) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 24168225, 28) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 24168225, 72) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 24768684, 49) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 24768684, 62) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 24768684, 27) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 24768684, 69) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 26267884, 67) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 26267884, 91) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 26267884, 41) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 27565696, 33) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 27807994, 63) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 27807994, 16) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 27807994, 38) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 27807994, 59) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 27807994, 20) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 27807994, 20) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 27807994, 59) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 28236059, 4) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 28236059, 18) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 28236059, 83) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 28236059, 15) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 28236059, 62) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 28236059, 26) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 28246742, 48) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 28256014, 40) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 28256014, 8) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 28256014, 60) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 28256014, 77) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 28256014, 50) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 28259903, 31) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 28259903, 81) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 28259903, 57) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 28259903, 46) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 28277194, 28) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 28277194, 5) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 28277194, 23) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 28277334, 4) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 28277334, 16) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 28277334, 10) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 28277334, 96) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 28277334, 51) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 28277334, 6) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 28277334, 57) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 28277334, 65) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 28298976, 47) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 28298976, 4) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 28298976, 78) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 28298976, 61) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 28298976, 32) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 28298976, 45) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 28306005, 86) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 28306005, 68) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 28306005, 49) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 28306005, 46) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 28306005, 80) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 28306005, 71) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 28306005, 33) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 28308068, 6) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 28325785, 88) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 28325785, 34) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 28325785, 98) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 28325785, 48) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 28325785, 62) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 28325785, 96) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 28325785, 31) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 28325785, 13) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 28325801, 74) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 28325801, 34) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 28325801, 58) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 28325801, 97) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 28325801, 23) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 28325801, 70) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 28325801, 55) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 28325801, 87) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 28326534, 68) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 28329170, 20) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 28329170, 71) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 28329170, 63) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 28329170, 66) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 28329170, 59) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 28337749, 55) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 28337749, 26) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 28345926, 5) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 28345926, 93) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 28345926, 6) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 28345926, 45) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 28345926, 92) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 28347396, 26) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 28347396, 74) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 28347396, 33) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 28347396, 34) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 28506967, 76) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 28506967, 42) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 28506967, 37) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 28506967, 6) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 28506967, 84) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 30088770, 83) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 30088770, 38) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 30115704, 78) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 30115704, 15) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 30115704, 82) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 30115704, 58) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 30816475, 34) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 30816475, 88) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 30816475, 83) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 30816475, 55) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 30816475, 75) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 30816475, 63) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 30816475, 59) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 31147466, 67) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 31147466, 44) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 31147466, 8) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 31147466, 65) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 31147466, 22) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 31279210, 43) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 31279210, 66) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 32605854, 12) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 32605854, 49) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 32605854, 9) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 32605854, 62) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 32605854, 96) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 32605854, 4) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 32605854, 5) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 32638658, 24) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 32638658, 66) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 32638658, 58) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 32638658, 26) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 32638658, 81) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 32638658, 32) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 32638658, 7) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 32638658, 32) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 32885918, 41) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 32885918, 20) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 32885918, 51) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 32885918, 44) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 32885918, 34) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 32885918, 36) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 33136552, 32) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 33136552, 28) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 33136552, 3) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 33136552, 72) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 33136552, 83) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 33136552, 58) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 33165704, 49) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 33165704, 45) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 33165704, 94) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 33165704, 91) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 33165704, 0) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 33165704, 7) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 33165704, 64) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 33658976, 46) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 33658976, 67) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 33658976, 87) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 33658976, 55) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 33658976, 32) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 33658976, 25) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 33658976, 74) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 33658976, 85) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 33716014, 20) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 34701976, 82) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 34701976, 11) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 135466315, 45) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 135567670, 81) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 135567670, 89) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 135567670, 10) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 135567670, 32) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 135717296, 7) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 135717296, 25) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 135717296, 49) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 135717296, 86) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 135717296, 78) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 135717466, 82) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 135717466, 25) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 135717466, 68) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 135717466, 54) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 135717466, 39) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 135717466, 18) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 135937324, 86) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 135937324, 46) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 135937324, 60) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 136607542, 80) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 136607542, 42) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 136607542, 89) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 136607542, 24) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 136607542, 24) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 136607542, 77) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 136776363, 46) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 136776363, 28) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 136776363, 56) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 136776363, 38) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 137527589, 58) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 137527589, 43) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 137527589, 60) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 137637384, 30) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 137637384, 24) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 137637384, 77) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 137637384, 6) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 137637384, 4) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 138135865, 38) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 138135865, 44) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 138135865, 68) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 138135865, 48) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 138135865, 89) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 138135865, 61) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 138135865, 59) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 138135865, 36) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 138187324, 61) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 138187324, 23) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 138187324, 58) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 138187324, 84) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 138187324, 38) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 138187324, 71) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 138187324, 91) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 138269011, 7) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (4, 138269011, 17) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 138269011, 14) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 138269011, 72) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 138269011, 30) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 138269011, 73) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 138269011, 11) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 138269011, 7) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 138486373, 40) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 138486373, 1) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (8, 138486373, 71) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (3, 138486373, 30) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 138486373, 32) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 138486373, 9) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (6, 138486373, 61) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 138486373, 93) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (9, 138498210, 9) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 138498210, 85) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (2, 138498210, 57) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (5, 138937510, 56) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 138937510, 42) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (7, 138937510, 85) ON CONFLICT (warehouse_id, sku) DO NOTHING;
INSERT INTO stocks (warehouse_id, sku, count) VALUES (1, 138937510, 42) ON CONFLICT (warehouse_id, sku) DO NOTHING;
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS public.stock;
DROP TABLE IF EXISTS public.stocks_reservation;
DROP TABLE IF EXISTS public.orders;
-- +goose StatementEnd
