// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i route256/checkout/internal/domain.LomsClient -o loms_client_minimock.go -n LomsClientMock -p mocks

import (
	"context"
	mm_domain "route256/checkout/internal/domain"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// LomsClientMock implements mm_domain.LomsClient
type LomsClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateOrder          func(ctx context.Context, user int64, items []mm_domain.OrderItem) (i1 int64, err error)
	funcCreateOrderOrigin    string
	inspectFuncCreateOrder   func(ctx context.Context, user int64, items []mm_domain.OrderItem)
	afterCreateOrderCounter  uint64
	beforeCreateOrderCounter uint64
	CreateOrderMock          mLomsClientMockCreateOrder

	funcStocks          func(ctx context.Context, sku uint32) (sa1 []mm_domain.Stock, err error)
	funcStocksOrigin    string
	inspectFuncStocks   func(ctx context.Context, sku uint32)
	afterStocksCounter  uint64
	beforeStocksCounter uint64
	StocksMock          mLomsClientMockStocks
}

// NewLomsClientMock returns a mock for mm_domain.LomsClient
func NewLomsClientMock(t minimock.Tester) *LomsClientMock {
	m := &LomsClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateOrderMock = mLomsClientMockCreateOrder{mock: m}
	m.CreateOrderMock.callArgs = []*LomsClientMockCreateOrderParams{}

	m.StocksMock = mLomsClientMockStocks{mock: m}
	m.StocksMock.callArgs = []*LomsClientMockStocksParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLomsClientMockCreateOrder struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockCreateOrderExpectation
	expectations       []*LomsClientMockCreateOrderExpectation

	callArgs []*LomsClientMockCreateOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockCreateOrderExpectation specifies expectation struct of the LomsClient.CreateOrder
type LomsClientMockCreateOrderExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockCreateOrderParams
	paramPtrs          *LomsClientMockCreateOrderParamPtrs
	expectationOrigins LomsClientMockCreateOrderExpectationOrigins
	results            *LomsClientMockCreateOrderResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockCreateOrderParams contains parameters of the LomsClient.CreateOrder
type LomsClientMockCreateOrderParams struct {
	ctx   context.Context
	user  int64
	items []mm_domain.OrderItem
}

// LomsClientMockCreateOrderParamPtrs contains pointers to parameters of the LomsClient.CreateOrder
type LomsClientMockCreateOrderParamPtrs struct {
	ctx   *context.Context
	user  *int64
	items *[]mm_domain.OrderItem
}

// LomsClientMockCreateOrderResults contains results of the LomsClient.CreateOrder
type LomsClientMockCreateOrderResults struct {
	i1  int64
	err error
}

// LomsClientMockCreateOrderOrigins contains origins of expectations of the LomsClient.CreateOrder
type LomsClientMockCreateOrderExpectationOrigins struct {
	origin      string
	originCtx   string
	originUser  string
	originItems string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateOrder *mLomsClientMockCreateOrder) Optional() *mLomsClientMockCreateOrder {
	mmCreateOrder.optional = true
	return mmCreateOrder
}

// Expect sets up expected params for LomsClient.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) Expect(ctx context.Context, user int64, items []mm_domain.OrderItem) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{}
	}

	if mmCreateOrder.defaultExpectation.paramPtrs != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by ExpectParams functions")
	}

	mmCreateOrder.defaultExpectation.params = &LomsClientMockCreateOrderParams{ctx, user, items}
	mmCreateOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateOrder.expectations {
		if minimock.Equal(e.params, mmCreateOrder.defaultExpectation.params) {
			mmCreateOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateOrder.defaultExpectation.params)
		}
	}

	return mmCreateOrder
}

// ExpectCtxParam1 sets up expected param ctx for LomsClient.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) ExpectCtxParam1(ctx context.Context) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{}
	}

	if mmCreateOrder.defaultExpectation.params != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Expect")
	}

	if mmCreateOrder.defaultExpectation.paramPtrs == nil {
		mmCreateOrder.defaultExpectation.paramPtrs = &LomsClientMockCreateOrderParamPtrs{}
	}
	mmCreateOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateOrder
}

// ExpectUserParam2 sets up expected param user for LomsClient.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) ExpectUserParam2(user int64) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{}
	}

	if mmCreateOrder.defaultExpectation.params != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Expect")
	}

	if mmCreateOrder.defaultExpectation.paramPtrs == nil {
		mmCreateOrder.defaultExpectation.paramPtrs = &LomsClientMockCreateOrderParamPtrs{}
	}
	mmCreateOrder.defaultExpectation.paramPtrs.user = &user
	mmCreateOrder.defaultExpectation.expectationOrigins.originUser = minimock.CallerInfo(1)

	return mmCreateOrder
}

// ExpectItemsParam3 sets up expected param items for LomsClient.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) ExpectItemsParam3(items []mm_domain.OrderItem) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{}
	}

	if mmCreateOrder.defaultExpectation.params != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Expect")
	}

	if mmCreateOrder.defaultExpectation.paramPtrs == nil {
		mmCreateOrder.defaultExpectation.paramPtrs = &LomsClientMockCreateOrderParamPtrs{}
	}
	mmCreateOrder.defaultExpectation.paramPtrs.items = &items
	mmCreateOrder.defaultExpectation.expectationOrigins.originItems = minimock.CallerInfo(1)

	return mmCreateOrder
}

// Inspect accepts an inspector function that has same arguments as the LomsClient.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) Inspect(f func(ctx context.Context, user int64, items []mm_domain.OrderItem)) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.inspectFuncCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("Inspect function is already set for LomsClientMock.CreateOrder")
	}

	mmCreateOrder.mock.inspectFuncCreateOrder = f

	return mmCreateOrder
}

// Return sets up results that will be returned by LomsClient.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) Return(i1 int64, err error) *LomsClientMock {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{mock: mmCreateOrder.mock}
	}
	mmCreateOrder.defaultExpectation.results = &LomsClientMockCreateOrderResults{i1, err}
	mmCreateOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateOrder.mock
}

// Set uses given function f to mock the LomsClient.CreateOrder method
func (mmCreateOrder *mLomsClientMockCreateOrder) Set(f func(ctx context.Context, user int64, items []mm_domain.OrderItem) (i1 int64, err error)) *LomsClientMock {
	if mmCreateOrder.defaultExpectation != nil {
		mmCreateOrder.mock.t.Fatalf("Default expectation is already set for the LomsClient.CreateOrder method")
	}

	if len(mmCreateOrder.expectations) > 0 {
		mmCreateOrder.mock.t.Fatalf("Some expectations are already set for the LomsClient.CreateOrder method")
	}

	mmCreateOrder.mock.funcCreateOrder = f
	mmCreateOrder.mock.funcCreateOrderOrigin = minimock.CallerInfo(1)
	return mmCreateOrder.mock
}

// When sets expectation for the LomsClient.CreateOrder which will trigger the result defined by the following
// Then helper
func (mmCreateOrder *mLomsClientMockCreateOrder) When(ctx context.Context, user int64, items []mm_domain.OrderItem) *LomsClientMockCreateOrderExpectation {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	expectation := &LomsClientMockCreateOrderExpectation{
		mock:               mmCreateOrder.mock,
		params:             &LomsClientMockCreateOrderParams{ctx, user, items},
		expectationOrigins: LomsClientMockCreateOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateOrder.expectations = append(mmCreateOrder.expectations, expectation)
	return expectation
}

// Then sets up LomsClient.CreateOrder return parameters for the expectation previously defined by the When method
func (e *LomsClientMockCreateOrderExpectation) Then(i1 int64, err error) *LomsClientMock {
	e.results = &LomsClientMockCreateOrderResults{i1, err}
	return e.mock
}

// Times sets number of times LomsClient.CreateOrder should be invoked
func (mmCreateOrder *mLomsClientMockCreateOrder) Times(n uint64) *mLomsClientMockCreateOrder {
	if n == 0 {
		mmCreateOrder.mock.t.Fatalf("Times of LomsClientMock.CreateOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateOrder.expectedInvocations, n)
	mmCreateOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateOrder
}

func (mmCreateOrder *mLomsClientMockCreateOrder) invocationsDone() bool {
	if len(mmCreateOrder.expectations) == 0 && mmCreateOrder.defaultExpectation == nil && mmCreateOrder.mock.funcCreateOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateOrder.mock.afterCreateOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateOrder implements mm_domain.LomsClient
func (mmCreateOrder *LomsClientMock) CreateOrder(ctx context.Context, user int64, items []mm_domain.OrderItem) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmCreateOrder.beforeCreateOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateOrder.afterCreateOrderCounter, 1)

	mmCreateOrder.t.Helper()

	if mmCreateOrder.inspectFuncCreateOrder != nil {
		mmCreateOrder.inspectFuncCreateOrder(ctx, user, items)
	}

	mm_params := LomsClientMockCreateOrderParams{ctx, user, items}

	// Record call args
	mmCreateOrder.CreateOrderMock.mutex.Lock()
	mmCreateOrder.CreateOrderMock.callArgs = append(mmCreateOrder.CreateOrderMock.callArgs, &mm_params)
	mmCreateOrder.CreateOrderMock.mutex.Unlock()

	for _, e := range mmCreateOrder.CreateOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmCreateOrder.CreateOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateOrder.CreateOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateOrder.CreateOrderMock.defaultExpectation.params
		mm_want_ptrs := mmCreateOrder.CreateOrderMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockCreateOrderParams{ctx, user, items}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateOrder.t.Errorf("LomsClientMock.CreateOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateOrder.CreateOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.user != nil && !minimock.Equal(*mm_want_ptrs.user, mm_got.user) {
				mmCreateOrder.t.Errorf("LomsClientMock.CreateOrder got unexpected parameter user, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateOrder.CreateOrderMock.defaultExpectation.expectationOrigins.originUser, *mm_want_ptrs.user, mm_got.user, minimock.Diff(*mm_want_ptrs.user, mm_got.user))
			}

			if mm_want_ptrs.items != nil && !minimock.Equal(*mm_want_ptrs.items, mm_got.items) {
				mmCreateOrder.t.Errorf("LomsClientMock.CreateOrder got unexpected parameter items, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateOrder.CreateOrderMock.defaultExpectation.expectationOrigins.originItems, *mm_want_ptrs.items, mm_got.items, minimock.Diff(*mm_want_ptrs.items, mm_got.items))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateOrder.t.Errorf("LomsClientMock.CreateOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateOrder.CreateOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateOrder.CreateOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateOrder.t.Fatal("No results are set for the LomsClientMock.CreateOrder")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmCreateOrder.funcCreateOrder != nil {
		return mmCreateOrder.funcCreateOrder(ctx, user, items)
	}
	mmCreateOrder.t.Fatalf("Unexpected call to LomsClientMock.CreateOrder. %v %v %v", ctx, user, items)
	return
}

// CreateOrderAfterCounter returns a count of finished LomsClientMock.CreateOrder invocations
func (mmCreateOrder *LomsClientMock) CreateOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.afterCreateOrderCounter)
}

// CreateOrderBeforeCounter returns a count of LomsClientMock.CreateOrder invocations
func (mmCreateOrder *LomsClientMock) CreateOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.beforeCreateOrderCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.CreateOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateOrder *mLomsClientMockCreateOrder) Calls() []*LomsClientMockCreateOrderParams {
	mmCreateOrder.mutex.RLock()

	argCopy := make([]*LomsClientMockCreateOrderParams, len(mmCreateOrder.callArgs))
	copy(argCopy, mmCreateOrder.callArgs)

	mmCreateOrder.mutex.RUnlock()

	return argCopy
}

// MinimockCreateOrderDone returns true if the count of the CreateOrder invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockCreateOrderDone() bool {
	if m.CreateOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateOrderMock.invocationsDone()
}

// MinimockCreateOrderInspect logs each unmet expectation
func (m *LomsClientMock) MinimockCreateOrderInspect() {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.CreateOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateOrderCounter := mm_atomic.LoadUint64(&m.afterCreateOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && afterCreateOrderCounter < 1 {
		if m.CreateOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.CreateOrder at\n%s", m.CreateOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.CreateOrder at\n%s with params: %#v", m.CreateOrderMock.defaultExpectation.expectationOrigins.origin, *m.CreateOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && afterCreateOrderCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.CreateOrder at\n%s", m.funcCreateOrderOrigin)
	}

	if !m.CreateOrderMock.invocationsDone() && afterCreateOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.CreateOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateOrderMock.expectedInvocations), m.CreateOrderMock.expectedInvocationsOrigin, afterCreateOrderCounter)
	}
}

type mLomsClientMockStocks struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockStocksExpectation
	expectations       []*LomsClientMockStocksExpectation

	callArgs []*LomsClientMockStocksParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockStocksExpectation specifies expectation struct of the LomsClient.Stocks
type LomsClientMockStocksExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockStocksParams
	paramPtrs          *LomsClientMockStocksParamPtrs
	expectationOrigins LomsClientMockStocksExpectationOrigins
	results            *LomsClientMockStocksResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockStocksParams contains parameters of the LomsClient.Stocks
type LomsClientMockStocksParams struct {
	ctx context.Context
	sku uint32
}

// LomsClientMockStocksParamPtrs contains pointers to parameters of the LomsClient.Stocks
type LomsClientMockStocksParamPtrs struct {
	ctx *context.Context
	sku *uint32
}

// LomsClientMockStocksResults contains results of the LomsClient.Stocks
type LomsClientMockStocksResults struct {
	sa1 []mm_domain.Stock
	err error
}

// LomsClientMockStocksOrigins contains origins of expectations of the LomsClient.Stocks
type LomsClientMockStocksExpectationOrigins struct {
	origin    string
	originCtx string
	originSku string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmStocks *mLomsClientMockStocks) Optional() *mLomsClientMockStocks {
	mmStocks.optional = true
	return mmStocks
}

// Expect sets up expected params for LomsClient.Stocks
func (mmStocks *mLomsClientMockStocks) Expect(ctx context.Context, sku uint32) *mLomsClientMockStocks {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LomsClientMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LomsClientMockStocksExpectation{}
	}

	if mmStocks.defaultExpectation.paramPtrs != nil {
		mmStocks.mock.t.Fatalf("LomsClientMock.Stocks mock is already set by ExpectParams functions")
	}

	mmStocks.defaultExpectation.params = &LomsClientMockStocksParams{ctx, sku}
	mmStocks.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmStocks.expectations {
		if minimock.Equal(e.params, mmStocks.defaultExpectation.params) {
			mmStocks.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmStocks.defaultExpectation.params)
		}
	}

	return mmStocks
}

// ExpectCtxParam1 sets up expected param ctx for LomsClient.Stocks
func (mmStocks *mLomsClientMockStocks) ExpectCtxParam1(ctx context.Context) *mLomsClientMockStocks {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LomsClientMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LomsClientMockStocksExpectation{}
	}

	if mmStocks.defaultExpectation.params != nil {
		mmStocks.mock.t.Fatalf("LomsClientMock.Stocks mock is already set by Expect")
	}

	if mmStocks.defaultExpectation.paramPtrs == nil {
		mmStocks.defaultExpectation.paramPtrs = &LomsClientMockStocksParamPtrs{}
	}
	mmStocks.defaultExpectation.paramPtrs.ctx = &ctx
	mmStocks.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmStocks
}

// ExpectSkuParam2 sets up expected param sku for LomsClient.Stocks
func (mmStocks *mLomsClientMockStocks) ExpectSkuParam2(sku uint32) *mLomsClientMockStocks {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LomsClientMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LomsClientMockStocksExpectation{}
	}

	if mmStocks.defaultExpectation.params != nil {
		mmStocks.mock.t.Fatalf("LomsClientMock.Stocks mock is already set by Expect")
	}

	if mmStocks.defaultExpectation.paramPtrs == nil {
		mmStocks.defaultExpectation.paramPtrs = &LomsClientMockStocksParamPtrs{}
	}
	mmStocks.defaultExpectation.paramPtrs.sku = &sku
	mmStocks.defaultExpectation.expectationOrigins.originSku = minimock.CallerInfo(1)

	return mmStocks
}

// Inspect accepts an inspector function that has same arguments as the LomsClient.Stocks
func (mmStocks *mLomsClientMockStocks) Inspect(f func(ctx context.Context, sku uint32)) *mLomsClientMockStocks {
	if mmStocks.mock.inspectFuncStocks != nil {
		mmStocks.mock.t.Fatalf("Inspect function is already set for LomsClientMock.Stocks")
	}

	mmStocks.mock.inspectFuncStocks = f

	return mmStocks
}

// Return sets up results that will be returned by LomsClient.Stocks
func (mmStocks *mLomsClientMockStocks) Return(sa1 []mm_domain.Stock, err error) *LomsClientMock {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LomsClientMock.Stocks mock is already set by Set")
	}

	if mmStocks.defaultExpectation == nil {
		mmStocks.defaultExpectation = &LomsClientMockStocksExpectation{mock: mmStocks.mock}
	}
	mmStocks.defaultExpectation.results = &LomsClientMockStocksResults{sa1, err}
	mmStocks.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmStocks.mock
}

// Set uses given function f to mock the LomsClient.Stocks method
func (mmStocks *mLomsClientMockStocks) Set(f func(ctx context.Context, sku uint32) (sa1 []mm_domain.Stock, err error)) *LomsClientMock {
	if mmStocks.defaultExpectation != nil {
		mmStocks.mock.t.Fatalf("Default expectation is already set for the LomsClient.Stocks method")
	}

	if len(mmStocks.expectations) > 0 {
		mmStocks.mock.t.Fatalf("Some expectations are already set for the LomsClient.Stocks method")
	}

	mmStocks.mock.funcStocks = f
	mmStocks.mock.funcStocksOrigin = minimock.CallerInfo(1)
	return mmStocks.mock
}

// When sets expectation for the LomsClient.Stocks which will trigger the result defined by the following
// Then helper
func (mmStocks *mLomsClientMockStocks) When(ctx context.Context, sku uint32) *LomsClientMockStocksExpectation {
	if mmStocks.mock.funcStocks != nil {
		mmStocks.mock.t.Fatalf("LomsClientMock.Stocks mock is already set by Set")
	}

	expectation := &LomsClientMockStocksExpectation{
		mock:               mmStocks.mock,
		params:             &LomsClientMockStocksParams{ctx, sku},
		expectationOrigins: LomsClientMockStocksExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmStocks.expectations = append(mmStocks.expectations, expectation)
	return expectation
}

// Then sets up LomsClient.Stocks return parameters for the expectation previously defined by the When method
func (e *LomsClientMockStocksExpectation) Then(sa1 []mm_domain.Stock, err error) *LomsClientMock {
	e.results = &LomsClientMockStocksResults{sa1, err}
	return e.mock
}

// Times sets number of times LomsClient.Stocks should be invoked
func (mmStocks *mLomsClientMockStocks) Times(n uint64) *mLomsClientMockStocks {
	if n == 0 {
		mmStocks.mock.t.Fatalf("Times of LomsClientMock.Stocks mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmStocks.expectedInvocations, n)
	mmStocks.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmStocks
}

func (mmStocks *mLomsClientMockStocks) invocationsDone() bool {
	if len(mmStocks.expectations) == 0 && mmStocks.defaultExpectation == nil && mmStocks.mock.funcStocks == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmStocks.mock.afterStocksCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmStocks.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Stocks implements mm_domain.LomsClient
func (mmStocks *LomsClientMock) Stocks(ctx context.Context, sku uint32) (sa1 []mm_domain.Stock, err error) {
	mm_atomic.AddUint64(&mmStocks.beforeStocksCounter, 1)
	defer mm_atomic.AddUint64(&mmStocks.afterStocksCounter, 1)

	mmStocks.t.Helper()

	if mmStocks.inspectFuncStocks != nil {
		mmStocks.inspectFuncStocks(ctx, sku)
	}

	mm_params := LomsClientMockStocksParams{ctx, sku}

	// Record call args
	mmStocks.StocksMock.mutex.Lock()
	mmStocks.StocksMock.callArgs = append(mmStocks.StocksMock.callArgs, &mm_params)
	mmStocks.StocksMock.mutex.Unlock()

	for _, e := range mmStocks.StocksMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sa1, e.results.err
		}
	}

	if mmStocks.StocksMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmStocks.StocksMock.defaultExpectation.Counter, 1)
		mm_want := mmStocks.StocksMock.defaultExpectation.params
		mm_want_ptrs := mmStocks.StocksMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockStocksParams{ctx, sku}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmStocks.t.Errorf("LomsClientMock.Stocks got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStocks.StocksMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sku != nil && !minimock.Equal(*mm_want_ptrs.sku, mm_got.sku) {
				mmStocks.t.Errorf("LomsClientMock.Stocks got unexpected parameter sku, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmStocks.StocksMock.defaultExpectation.expectationOrigins.originSku, *mm_want_ptrs.sku, mm_got.sku, minimock.Diff(*mm_want_ptrs.sku, mm_got.sku))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmStocks.t.Errorf("LomsClientMock.Stocks got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmStocks.StocksMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmStocks.StocksMock.defaultExpectation.results
		if mm_results == nil {
			mmStocks.t.Fatal("No results are set for the LomsClientMock.Stocks")
		}
		return (*mm_results).sa1, (*mm_results).err
	}
	if mmStocks.funcStocks != nil {
		return mmStocks.funcStocks(ctx, sku)
	}
	mmStocks.t.Fatalf("Unexpected call to LomsClientMock.Stocks. %v %v", ctx, sku)
	return
}

// StocksAfterCounter returns a count of finished LomsClientMock.Stocks invocations
func (mmStocks *LomsClientMock) StocksAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.afterStocksCounter)
}

// StocksBeforeCounter returns a count of LomsClientMock.Stocks invocations
func (mmStocks *LomsClientMock) StocksBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmStocks.beforeStocksCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.Stocks.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmStocks *mLomsClientMockStocks) Calls() []*LomsClientMockStocksParams {
	mmStocks.mutex.RLock()

	argCopy := make([]*LomsClientMockStocksParams, len(mmStocks.callArgs))
	copy(argCopy, mmStocks.callArgs)

	mmStocks.mutex.RUnlock()

	return argCopy
}

// MinimockStocksDone returns true if the count of the Stocks invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockStocksDone() bool {
	if m.StocksMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.StocksMock.invocationsDone()
}

// MinimockStocksInspect logs each unmet expectation
func (m *LomsClientMock) MinimockStocksInspect() {
	for _, e := range m.StocksMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.Stocks at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterStocksCounter := mm_atomic.LoadUint64(&m.afterStocksCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.StocksMock.defaultExpectation != nil && afterStocksCounter < 1 {
		if m.StocksMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.Stocks at\n%s", m.StocksMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.Stocks at\n%s with params: %#v", m.StocksMock.defaultExpectation.expectationOrigins.origin, *m.StocksMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcStocks != nil && afterStocksCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.Stocks at\n%s", m.funcStocksOrigin)
	}

	if !m.StocksMock.invocationsDone() && afterStocksCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.Stocks at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.StocksMock.expectedInvocations), m.StocksMock.expectedInvocationsOrigin, afterStocksCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LomsClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateOrderInspect()

			m.MinimockStocksInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LomsClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LomsClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateOrderDone() &&
		m.MinimockStocksDone()
}
