// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i route256/checkout/internal/domain.ProductServiceClient -o product_service_client_minimock.go -n ProductServiceClientMock -p mocks

import (
	"context"
	mm_domain "route256/checkout/internal/domain"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ProductServiceClientMock implements mm_domain.ProductServiceClient
type ProductServiceClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcProduct          func(ctx context.Context, sku uint32) (p1 mm_domain.Product, err error)
	funcProductOrigin    string
	inspectFuncProduct   func(ctx context.Context, sku uint32)
	afterProductCounter  uint64
	beforeProductCounter uint64
	ProductMock          mProductServiceClientMockProduct
}

// NewProductServiceClientMock returns a mock for mm_domain.ProductServiceClient
func NewProductServiceClientMock(t minimock.Tester) *ProductServiceClientMock {
	m := &ProductServiceClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ProductMock = mProductServiceClientMockProduct{mock: m}
	m.ProductMock.callArgs = []*ProductServiceClientMockProductParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mProductServiceClientMockProduct struct {
	optional           bool
	mock               *ProductServiceClientMock
	defaultExpectation *ProductServiceClientMockProductExpectation
	expectations       []*ProductServiceClientMockProductExpectation

	callArgs []*ProductServiceClientMockProductParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// ProductServiceClientMockProductExpectation specifies expectation struct of the ProductServiceClient.Product
type ProductServiceClientMockProductExpectation struct {
	mock               *ProductServiceClientMock
	params             *ProductServiceClientMockProductParams
	paramPtrs          *ProductServiceClientMockProductParamPtrs
	expectationOrigins ProductServiceClientMockProductExpectationOrigins
	results            *ProductServiceClientMockProductResults
	returnOrigin       string
	Counter            uint64
}

// ProductServiceClientMockProductParams contains parameters of the ProductServiceClient.Product
type ProductServiceClientMockProductParams struct {
	ctx context.Context
	sku uint32
}

// ProductServiceClientMockProductParamPtrs contains pointers to parameters of the ProductServiceClient.Product
type ProductServiceClientMockProductParamPtrs struct {
	ctx *context.Context
	sku *uint32
}

// ProductServiceClientMockProductResults contains results of the ProductServiceClient.Product
type ProductServiceClientMockProductResults struct {
	p1  mm_domain.Product
	err error
}

// ProductServiceClientMockProductOrigins contains origins of expectations of the ProductServiceClient.Product
type ProductServiceClientMockProductExpectationOrigins struct {
	origin    string
	originCtx string
	originSku string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmProduct *mProductServiceClientMockProduct) Optional() *mProductServiceClientMockProduct {
	mmProduct.optional = true
	return mmProduct
}

// Expect sets up expected params for ProductServiceClient.Product
func (mmProduct *mProductServiceClientMockProduct) Expect(ctx context.Context, sku uint32) *mProductServiceClientMockProduct {
	if mmProduct.mock.funcProduct != nil {
		mmProduct.mock.t.Fatalf("ProductServiceClientMock.Product mock is already set by Set")
	}

	if mmProduct.defaultExpectation == nil {
		mmProduct.defaultExpectation = &ProductServiceClientMockProductExpectation{}
	}

	if mmProduct.defaultExpectation.paramPtrs != nil {
		mmProduct.mock.t.Fatalf("ProductServiceClientMock.Product mock is already set by ExpectParams functions")
	}

	mmProduct.defaultExpectation.params = &ProductServiceClientMockProductParams{ctx, sku}
	mmProduct.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmProduct.expectations {
		if minimock.Equal(e.params, mmProduct.defaultExpectation.params) {
			mmProduct.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmProduct.defaultExpectation.params)
		}
	}

	return mmProduct
}

// ExpectCtxParam1 sets up expected param ctx for ProductServiceClient.Product
func (mmProduct *mProductServiceClientMockProduct) ExpectCtxParam1(ctx context.Context) *mProductServiceClientMockProduct {
	if mmProduct.mock.funcProduct != nil {
		mmProduct.mock.t.Fatalf("ProductServiceClientMock.Product mock is already set by Set")
	}

	if mmProduct.defaultExpectation == nil {
		mmProduct.defaultExpectation = &ProductServiceClientMockProductExpectation{}
	}

	if mmProduct.defaultExpectation.params != nil {
		mmProduct.mock.t.Fatalf("ProductServiceClientMock.Product mock is already set by Expect")
	}

	if mmProduct.defaultExpectation.paramPtrs == nil {
		mmProduct.defaultExpectation.paramPtrs = &ProductServiceClientMockProductParamPtrs{}
	}
	mmProduct.defaultExpectation.paramPtrs.ctx = &ctx
	mmProduct.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmProduct
}

// ExpectSkuParam2 sets up expected param sku for ProductServiceClient.Product
func (mmProduct *mProductServiceClientMockProduct) ExpectSkuParam2(sku uint32) *mProductServiceClientMockProduct {
	if mmProduct.mock.funcProduct != nil {
		mmProduct.mock.t.Fatalf("ProductServiceClientMock.Product mock is already set by Set")
	}

	if mmProduct.defaultExpectation == nil {
		mmProduct.defaultExpectation = &ProductServiceClientMockProductExpectation{}
	}

	if mmProduct.defaultExpectation.params != nil {
		mmProduct.mock.t.Fatalf("ProductServiceClientMock.Product mock is already set by Expect")
	}

	if mmProduct.defaultExpectation.paramPtrs == nil {
		mmProduct.defaultExpectation.paramPtrs = &ProductServiceClientMockProductParamPtrs{}
	}
	mmProduct.defaultExpectation.paramPtrs.sku = &sku
	mmProduct.defaultExpectation.expectationOrigins.originSku = minimock.CallerInfo(1)

	return mmProduct
}

// Inspect accepts an inspector function that has same arguments as the ProductServiceClient.Product
func (mmProduct *mProductServiceClientMockProduct) Inspect(f func(ctx context.Context, sku uint32)) *mProductServiceClientMockProduct {
	if mmProduct.mock.inspectFuncProduct != nil {
		mmProduct.mock.t.Fatalf("Inspect function is already set for ProductServiceClientMock.Product")
	}

	mmProduct.mock.inspectFuncProduct = f

	return mmProduct
}

// Return sets up results that will be returned by ProductServiceClient.Product
func (mmProduct *mProductServiceClientMockProduct) Return(p1 mm_domain.Product, err error) *ProductServiceClientMock {
	if mmProduct.mock.funcProduct != nil {
		mmProduct.mock.t.Fatalf("ProductServiceClientMock.Product mock is already set by Set")
	}

	if mmProduct.defaultExpectation == nil {
		mmProduct.defaultExpectation = &ProductServiceClientMockProductExpectation{mock: mmProduct.mock}
	}
	mmProduct.defaultExpectation.results = &ProductServiceClientMockProductResults{p1, err}
	mmProduct.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmProduct.mock
}

// Set uses given function f to mock the ProductServiceClient.Product method
func (mmProduct *mProductServiceClientMockProduct) Set(f func(ctx context.Context, sku uint32) (p1 mm_domain.Product, err error)) *ProductServiceClientMock {
	if mmProduct.defaultExpectation != nil {
		mmProduct.mock.t.Fatalf("Default expectation is already set for the ProductServiceClient.Product method")
	}

	if len(mmProduct.expectations) > 0 {
		mmProduct.mock.t.Fatalf("Some expectations are already set for the ProductServiceClient.Product method")
	}

	mmProduct.mock.funcProduct = f
	mmProduct.mock.funcProductOrigin = minimock.CallerInfo(1)
	return mmProduct.mock
}

// When sets expectation for the ProductServiceClient.Product which will trigger the result defined by the following
// Then helper
func (mmProduct *mProductServiceClientMockProduct) When(ctx context.Context, sku uint32) *ProductServiceClientMockProductExpectation {
	if mmProduct.mock.funcProduct != nil {
		mmProduct.mock.t.Fatalf("ProductServiceClientMock.Product mock is already set by Set")
	}

	expectation := &ProductServiceClientMockProductExpectation{
		mock:               mmProduct.mock,
		params:             &ProductServiceClientMockProductParams{ctx, sku},
		expectationOrigins: ProductServiceClientMockProductExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmProduct.expectations = append(mmProduct.expectations, expectation)
	return expectation
}

// Then sets up ProductServiceClient.Product return parameters for the expectation previously defined by the When method
func (e *ProductServiceClientMockProductExpectation) Then(p1 mm_domain.Product, err error) *ProductServiceClientMock {
	e.results = &ProductServiceClientMockProductResults{p1, err}
	return e.mock
}

// Times sets number of times ProductServiceClient.Product should be invoked
func (mmProduct *mProductServiceClientMockProduct) Times(n uint64) *mProductServiceClientMockProduct {
	if n == 0 {
		mmProduct.mock.t.Fatalf("Times of ProductServiceClientMock.Product mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmProduct.expectedInvocations, n)
	mmProduct.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmProduct
}

func (mmProduct *mProductServiceClientMockProduct) invocationsDone() bool {
	if len(mmProduct.expectations) == 0 && mmProduct.defaultExpectation == nil && mmProduct.mock.funcProduct == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmProduct.mock.afterProductCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmProduct.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Product implements mm_domain.ProductServiceClient
func (mmProduct *ProductServiceClientMock) Product(ctx context.Context, sku uint32) (p1 mm_domain.Product, err error) {
	mm_atomic.AddUint64(&mmProduct.beforeProductCounter, 1)
	defer mm_atomic.AddUint64(&mmProduct.afterProductCounter, 1)

	mmProduct.t.Helper()

	if mmProduct.inspectFuncProduct != nil {
		mmProduct.inspectFuncProduct(ctx, sku)
	}

	mm_params := ProductServiceClientMockProductParams{ctx, sku}

	// Record call args
	mmProduct.ProductMock.mutex.Lock()
	mmProduct.ProductMock.callArgs = append(mmProduct.ProductMock.callArgs, &mm_params)
	mmProduct.ProductMock.mutex.Unlock()

	for _, e := range mmProduct.ProductMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.p1, e.results.err
		}
	}

	if mmProduct.ProductMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmProduct.ProductMock.defaultExpectation.Counter, 1)
		mm_want := mmProduct.ProductMock.defaultExpectation.params
		mm_want_ptrs := mmProduct.ProductMock.defaultExpectation.paramPtrs

		mm_got := ProductServiceClientMockProductParams{ctx, sku}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmProduct.t.Errorf("ProductServiceClientMock.Product got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmProduct.ProductMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.sku != nil && !minimock.Equal(*mm_want_ptrs.sku, mm_got.sku) {
				mmProduct.t.Errorf("ProductServiceClientMock.Product got unexpected parameter sku, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmProduct.ProductMock.defaultExpectation.expectationOrigins.originSku, *mm_want_ptrs.sku, mm_got.sku, minimock.Diff(*mm_want_ptrs.sku, mm_got.sku))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmProduct.t.Errorf("ProductServiceClientMock.Product got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmProduct.ProductMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmProduct.ProductMock.defaultExpectation.results
		if mm_results == nil {
			mmProduct.t.Fatal("No results are set for the ProductServiceClientMock.Product")
		}
		return (*mm_results).p1, (*mm_results).err
	}
	if mmProduct.funcProduct != nil {
		return mmProduct.funcProduct(ctx, sku)
	}
	mmProduct.t.Fatalf("Unexpected call to ProductServiceClientMock.Product. %v %v", ctx, sku)
	return
}

// ProductAfterCounter returns a count of finished ProductServiceClientMock.Product invocations
func (mmProduct *ProductServiceClientMock) ProductAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmProduct.afterProductCounter)
}

// ProductBeforeCounter returns a count of ProductServiceClientMock.Product invocations
func (mmProduct *ProductServiceClientMock) ProductBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmProduct.beforeProductCounter)
}

// Calls returns a list of arguments used in each call to ProductServiceClientMock.Product.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmProduct *mProductServiceClientMockProduct) Calls() []*ProductServiceClientMockProductParams {
	mmProduct.mutex.RLock()

	argCopy := make([]*ProductServiceClientMockProductParams, len(mmProduct.callArgs))
	copy(argCopy, mmProduct.callArgs)

	mmProduct.mutex.RUnlock()

	return argCopy
}

// MinimockProductDone returns true if the count of the Product invocations corresponds
// the number of defined expectations
func (m *ProductServiceClientMock) MinimockProductDone() bool {
	if m.ProductMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ProductMock.invocationsDone()
}

// MinimockProductInspect logs each unmet expectation
func (m *ProductServiceClientMock) MinimockProductInspect() {
	for _, e := range m.ProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ProductServiceClientMock.Product at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterProductCounter := mm_atomic.LoadUint64(&m.afterProductCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ProductMock.defaultExpectation != nil && afterProductCounter < 1 {
		if m.ProductMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to ProductServiceClientMock.Product at\n%s", m.ProductMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to ProductServiceClientMock.Product at\n%s with params: %#v", m.ProductMock.defaultExpectation.expectationOrigins.origin, *m.ProductMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcProduct != nil && afterProductCounter < 1 {
		m.t.Errorf("Expected call to ProductServiceClientMock.Product at\n%s", m.funcProductOrigin)
	}

	if !m.ProductMock.invocationsDone() && afterProductCounter > 0 {
		m.t.Errorf("Expected %d calls to ProductServiceClientMock.Product at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ProductMock.expectedInvocations), m.ProductMock.expectedInvocationsOrigin, afterProductCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ProductServiceClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockProductInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ProductServiceClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ProductServiceClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockProductDone()
}
