// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package mocks

//go:generate minimock -i route256/checkout/internal/domain.TransactionManager -o transaction_manager_minimock.go -n TransactionManagerMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// TransactionManagerMock implements mm_domain.TransactionManager
type TransactionManagerMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcRunRepeteableReade          func(ctx context.Context, f func(ctxTX context.Context) error) (err error)
	funcRunRepeteableReadeOrigin    string
	inspectFuncRunRepeteableReade   func(ctx context.Context, f func(ctxTX context.Context) error)
	afterRunRepeteableReadeCounter  uint64
	beforeRunRepeteableReadeCounter uint64
	RunRepeteableReadeMock          mTransactionManagerMockRunRepeteableReade
}

// NewTransactionManagerMock returns a mock for mm_domain.TransactionManager
func NewTransactionManagerMock(t minimock.Tester) *TransactionManagerMock {
	m := &TransactionManagerMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.RunRepeteableReadeMock = mTransactionManagerMockRunRepeteableReade{mock: m}
	m.RunRepeteableReadeMock.callArgs = []*TransactionManagerMockRunRepeteableReadeParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTransactionManagerMockRunRepeteableReade struct {
	optional           bool
	mock               *TransactionManagerMock
	defaultExpectation *TransactionManagerMockRunRepeteableReadeExpectation
	expectations       []*TransactionManagerMockRunRepeteableReadeExpectation

	callArgs []*TransactionManagerMockRunRepeteableReadeParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TransactionManagerMockRunRepeteableReadeExpectation specifies expectation struct of the TransactionManager.RunRepeteableReade
type TransactionManagerMockRunRepeteableReadeExpectation struct {
	mock               *TransactionManagerMock
	params             *TransactionManagerMockRunRepeteableReadeParams
	paramPtrs          *TransactionManagerMockRunRepeteableReadeParamPtrs
	expectationOrigins TransactionManagerMockRunRepeteableReadeExpectationOrigins
	results            *TransactionManagerMockRunRepeteableReadeResults
	returnOrigin       string
	Counter            uint64
}

// TransactionManagerMockRunRepeteableReadeParams contains parameters of the TransactionManager.RunRepeteableReade
type TransactionManagerMockRunRepeteableReadeParams struct {
	ctx context.Context
	f   func(ctxTX context.Context) error
}

// TransactionManagerMockRunRepeteableReadeParamPtrs contains pointers to parameters of the TransactionManager.RunRepeteableReade
type TransactionManagerMockRunRepeteableReadeParamPtrs struct {
	ctx *context.Context
	f   *func(ctxTX context.Context) error
}

// TransactionManagerMockRunRepeteableReadeResults contains results of the TransactionManager.RunRepeteableReade
type TransactionManagerMockRunRepeteableReadeResults struct {
	err error
}

// TransactionManagerMockRunRepeteableReadeOrigins contains origins of expectations of the TransactionManager.RunRepeteableReade
type TransactionManagerMockRunRepeteableReadeExpectationOrigins struct {
	origin    string
	originCtx string
	originF   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmRunRepeteableReade *mTransactionManagerMockRunRepeteableReade) Optional() *mTransactionManagerMockRunRepeteableReade {
	mmRunRepeteableReade.optional = true
	return mmRunRepeteableReade
}

// Expect sets up expected params for TransactionManager.RunRepeteableReade
func (mmRunRepeteableReade *mTransactionManagerMockRunRepeteableReade) Expect(ctx context.Context, f func(ctxTX context.Context) error) *mTransactionManagerMockRunRepeteableReade {
	if mmRunRepeteableReade.mock.funcRunRepeteableReade != nil {
		mmRunRepeteableReade.mock.t.Fatalf("TransactionManagerMock.RunRepeteableReade mock is already set by Set")
	}

	if mmRunRepeteableReade.defaultExpectation == nil {
		mmRunRepeteableReade.defaultExpectation = &TransactionManagerMockRunRepeteableReadeExpectation{}
	}

	if mmRunRepeteableReade.defaultExpectation.paramPtrs != nil {
		mmRunRepeteableReade.mock.t.Fatalf("TransactionManagerMock.RunRepeteableReade mock is already set by ExpectParams functions")
	}

	mmRunRepeteableReade.defaultExpectation.params = &TransactionManagerMockRunRepeteableReadeParams{ctx, f}
	mmRunRepeteableReade.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmRunRepeteableReade.expectations {
		if minimock.Equal(e.params, mmRunRepeteableReade.defaultExpectation.params) {
			mmRunRepeteableReade.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmRunRepeteableReade.defaultExpectation.params)
		}
	}

	return mmRunRepeteableReade
}

// ExpectCtxParam1 sets up expected param ctx for TransactionManager.RunRepeteableReade
func (mmRunRepeteableReade *mTransactionManagerMockRunRepeteableReade) ExpectCtxParam1(ctx context.Context) *mTransactionManagerMockRunRepeteableReade {
	if mmRunRepeteableReade.mock.funcRunRepeteableReade != nil {
		mmRunRepeteableReade.mock.t.Fatalf("TransactionManagerMock.RunRepeteableReade mock is already set by Set")
	}

	if mmRunRepeteableReade.defaultExpectation == nil {
		mmRunRepeteableReade.defaultExpectation = &TransactionManagerMockRunRepeteableReadeExpectation{}
	}

	if mmRunRepeteableReade.defaultExpectation.params != nil {
		mmRunRepeteableReade.mock.t.Fatalf("TransactionManagerMock.RunRepeteableReade mock is already set by Expect")
	}

	if mmRunRepeteableReade.defaultExpectation.paramPtrs == nil {
		mmRunRepeteableReade.defaultExpectation.paramPtrs = &TransactionManagerMockRunRepeteableReadeParamPtrs{}
	}
	mmRunRepeteableReade.defaultExpectation.paramPtrs.ctx = &ctx
	mmRunRepeteableReade.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmRunRepeteableReade
}

// ExpectFParam2 sets up expected param f for TransactionManager.RunRepeteableReade
func (mmRunRepeteableReade *mTransactionManagerMockRunRepeteableReade) ExpectFParam2(f func(ctxTX context.Context) error) *mTransactionManagerMockRunRepeteableReade {
	if mmRunRepeteableReade.mock.funcRunRepeteableReade != nil {
		mmRunRepeteableReade.mock.t.Fatalf("TransactionManagerMock.RunRepeteableReade mock is already set by Set")
	}

	if mmRunRepeteableReade.defaultExpectation == nil {
		mmRunRepeteableReade.defaultExpectation = &TransactionManagerMockRunRepeteableReadeExpectation{}
	}

	if mmRunRepeteableReade.defaultExpectation.params != nil {
		mmRunRepeteableReade.mock.t.Fatalf("TransactionManagerMock.RunRepeteableReade mock is already set by Expect")
	}

	if mmRunRepeteableReade.defaultExpectation.paramPtrs == nil {
		mmRunRepeteableReade.defaultExpectation.paramPtrs = &TransactionManagerMockRunRepeteableReadeParamPtrs{}
	}
	mmRunRepeteableReade.defaultExpectation.paramPtrs.f = &f
	mmRunRepeteableReade.defaultExpectation.expectationOrigins.originF = minimock.CallerInfo(1)

	return mmRunRepeteableReade
}

// Inspect accepts an inspector function that has same arguments as the TransactionManager.RunRepeteableReade
func (mmRunRepeteableReade *mTransactionManagerMockRunRepeteableReade) Inspect(f func(ctx context.Context, f func(ctxTX context.Context) error)) *mTransactionManagerMockRunRepeteableReade {
	if mmRunRepeteableReade.mock.inspectFuncRunRepeteableReade != nil {
		mmRunRepeteableReade.mock.t.Fatalf("Inspect function is already set for TransactionManagerMock.RunRepeteableReade")
	}

	mmRunRepeteableReade.mock.inspectFuncRunRepeteableReade = f

	return mmRunRepeteableReade
}

// Return sets up results that will be returned by TransactionManager.RunRepeteableReade
func (mmRunRepeteableReade *mTransactionManagerMockRunRepeteableReade) Return(err error) *TransactionManagerMock {
	if mmRunRepeteableReade.mock.funcRunRepeteableReade != nil {
		mmRunRepeteableReade.mock.t.Fatalf("TransactionManagerMock.RunRepeteableReade mock is already set by Set")
	}

	if mmRunRepeteableReade.defaultExpectation == nil {
		mmRunRepeteableReade.defaultExpectation = &TransactionManagerMockRunRepeteableReadeExpectation{mock: mmRunRepeteableReade.mock}
	}
	mmRunRepeteableReade.defaultExpectation.results = &TransactionManagerMockRunRepeteableReadeResults{err}
	mmRunRepeteableReade.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmRunRepeteableReade.mock
}

// Set uses given function f to mock the TransactionManager.RunRepeteableReade method
func (mmRunRepeteableReade *mTransactionManagerMockRunRepeteableReade) Set(f func(ctx context.Context, f func(ctxTX context.Context) error) (err error)) *TransactionManagerMock {
	if mmRunRepeteableReade.defaultExpectation != nil {
		mmRunRepeteableReade.mock.t.Fatalf("Default expectation is already set for the TransactionManager.RunRepeteableReade method")
	}

	if len(mmRunRepeteableReade.expectations) > 0 {
		mmRunRepeteableReade.mock.t.Fatalf("Some expectations are already set for the TransactionManager.RunRepeteableReade method")
	}

	mmRunRepeteableReade.mock.funcRunRepeteableReade = f
	mmRunRepeteableReade.mock.funcRunRepeteableReadeOrigin = minimock.CallerInfo(1)
	return mmRunRepeteableReade.mock
}

// When sets expectation for the TransactionManager.RunRepeteableReade which will trigger the result defined by the following
// Then helper
func (mmRunRepeteableReade *mTransactionManagerMockRunRepeteableReade) When(ctx context.Context, f func(ctxTX context.Context) error) *TransactionManagerMockRunRepeteableReadeExpectation {
	if mmRunRepeteableReade.mock.funcRunRepeteableReade != nil {
		mmRunRepeteableReade.mock.t.Fatalf("TransactionManagerMock.RunRepeteableReade mock is already set by Set")
	}

	expectation := &TransactionManagerMockRunRepeteableReadeExpectation{
		mock:               mmRunRepeteableReade.mock,
		params:             &TransactionManagerMockRunRepeteableReadeParams{ctx, f},
		expectationOrigins: TransactionManagerMockRunRepeteableReadeExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmRunRepeteableReade.expectations = append(mmRunRepeteableReade.expectations, expectation)
	return expectation
}

// Then sets up TransactionManager.RunRepeteableReade return parameters for the expectation previously defined by the When method
func (e *TransactionManagerMockRunRepeteableReadeExpectation) Then(err error) *TransactionManagerMock {
	e.results = &TransactionManagerMockRunRepeteableReadeResults{err}
	return e.mock
}

// Times sets number of times TransactionManager.RunRepeteableReade should be invoked
func (mmRunRepeteableReade *mTransactionManagerMockRunRepeteableReade) Times(n uint64) *mTransactionManagerMockRunRepeteableReade {
	if n == 0 {
		mmRunRepeteableReade.mock.t.Fatalf("Times of TransactionManagerMock.RunRepeteableReade mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmRunRepeteableReade.expectedInvocations, n)
	mmRunRepeteableReade.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmRunRepeteableReade
}

func (mmRunRepeteableReade *mTransactionManagerMockRunRepeteableReade) invocationsDone() bool {
	if len(mmRunRepeteableReade.expectations) == 0 && mmRunRepeteableReade.defaultExpectation == nil && mmRunRepeteableReade.mock.funcRunRepeteableReade == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmRunRepeteableReade.mock.afterRunRepeteableReadeCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmRunRepeteableReade.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// RunRepeteableReade implements mm_domain.TransactionManager
func (mmRunRepeteableReade *TransactionManagerMock) RunRepeteableReade(ctx context.Context, f func(ctxTX context.Context) error) (err error) {
	mm_atomic.AddUint64(&mmRunRepeteableReade.beforeRunRepeteableReadeCounter, 1)
	defer mm_atomic.AddUint64(&mmRunRepeteableReade.afterRunRepeteableReadeCounter, 1)

	mmRunRepeteableReade.t.Helper()

	if mmRunRepeteableReade.inspectFuncRunRepeteableReade != nil {
		mmRunRepeteableReade.inspectFuncRunRepeteableReade(ctx, f)
	}

	mm_params := TransactionManagerMockRunRepeteableReadeParams{ctx, f}

	// Record call args
	mmRunRepeteableReade.RunRepeteableReadeMock.mutex.Lock()
	mmRunRepeteableReade.RunRepeteableReadeMock.callArgs = append(mmRunRepeteableReade.RunRepeteableReadeMock.callArgs, &mm_params)
	mmRunRepeteableReade.RunRepeteableReadeMock.mutex.Unlock()

	for _, e := range mmRunRepeteableReade.RunRepeteableReadeMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmRunRepeteableReade.RunRepeteableReadeMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmRunRepeteableReade.RunRepeteableReadeMock.defaultExpectation.Counter, 1)
		mm_want := mmRunRepeteableReade.RunRepeteableReadeMock.defaultExpectation.params
		mm_want_ptrs := mmRunRepeteableReade.RunRepeteableReadeMock.defaultExpectation.paramPtrs

		mm_got := TransactionManagerMockRunRepeteableReadeParams{ctx, f}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmRunRepeteableReade.t.Errorf("TransactionManagerMock.RunRepeteableReade got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRunRepeteableReade.RunRepeteableReadeMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.f != nil && !minimock.Equal(*mm_want_ptrs.f, mm_got.f) {
				mmRunRepeteableReade.t.Errorf("TransactionManagerMock.RunRepeteableReade got unexpected parameter f, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmRunRepeteableReade.RunRepeteableReadeMock.defaultExpectation.expectationOrigins.originF, *mm_want_ptrs.f, mm_got.f, minimock.Diff(*mm_want_ptrs.f, mm_got.f))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmRunRepeteableReade.t.Errorf("TransactionManagerMock.RunRepeteableReade got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmRunRepeteableReade.RunRepeteableReadeMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmRunRepeteableReade.RunRepeteableReadeMock.defaultExpectation.results
		if mm_results == nil {
			mmRunRepeteableReade.t.Fatal("No results are set for the TransactionManagerMock.RunRepeteableReade")
		}
		return (*mm_results).err
	}
	if mmRunRepeteableReade.funcRunRepeteableReade != nil {
		return mmRunRepeteableReade.funcRunRepeteableReade(ctx, f)
	}
	mmRunRepeteableReade.t.Fatalf("Unexpected call to TransactionManagerMock.RunRepeteableReade. %v %v", ctx, f)
	return
}

// RunRepeteableReadeAfterCounter returns a count of finished TransactionManagerMock.RunRepeteableReade invocations
func (mmRunRepeteableReade *TransactionManagerMock) RunRepeteableReadeAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRunRepeteableReade.afterRunRepeteableReadeCounter)
}

// RunRepeteableReadeBeforeCounter returns a count of TransactionManagerMock.RunRepeteableReade invocations
func (mmRunRepeteableReade *TransactionManagerMock) RunRepeteableReadeBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmRunRepeteableReade.beforeRunRepeteableReadeCounter)
}

// Calls returns a list of arguments used in each call to TransactionManagerMock.RunRepeteableReade.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmRunRepeteableReade *mTransactionManagerMockRunRepeteableReade) Calls() []*TransactionManagerMockRunRepeteableReadeParams {
	mmRunRepeteableReade.mutex.RLock()

	argCopy := make([]*TransactionManagerMockRunRepeteableReadeParams, len(mmRunRepeteableReade.callArgs))
	copy(argCopy, mmRunRepeteableReade.callArgs)

	mmRunRepeteableReade.mutex.RUnlock()

	return argCopy
}

// MinimockRunRepeteableReadeDone returns true if the count of the RunRepeteableReade invocations corresponds
// the number of defined expectations
func (m *TransactionManagerMock) MinimockRunRepeteableReadeDone() bool {
	if m.RunRepeteableReadeMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.RunRepeteableReadeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.RunRepeteableReadeMock.invocationsDone()
}

// MinimockRunRepeteableReadeInspect logs each unmet expectation
func (m *TransactionManagerMock) MinimockRunRepeteableReadeInspect() {
	for _, e := range m.RunRepeteableReadeMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TransactionManagerMock.RunRepeteableReade at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterRunRepeteableReadeCounter := mm_atomic.LoadUint64(&m.afterRunRepeteableReadeCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.RunRepeteableReadeMock.defaultExpectation != nil && afterRunRepeteableReadeCounter < 1 {
		if m.RunRepeteableReadeMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TransactionManagerMock.RunRepeteableReade at\n%s", m.RunRepeteableReadeMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TransactionManagerMock.RunRepeteableReade at\n%s with params: %#v", m.RunRepeteableReadeMock.defaultExpectation.expectationOrigins.origin, *m.RunRepeteableReadeMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcRunRepeteableReade != nil && afterRunRepeteableReadeCounter < 1 {
		m.t.Errorf("Expected call to TransactionManagerMock.RunRepeteableReade at\n%s", m.funcRunRepeteableReadeOrigin)
	}

	if !m.RunRepeteableReadeMock.invocationsDone() && afterRunRepeteableReadeCounter > 0 {
		m.t.Errorf("Expected %d calls to TransactionManagerMock.RunRepeteableReade at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.RunRepeteableReadeMock.expectedInvocations), m.RunRepeteableReadeMock.expectedInvocationsOrigin, afterRunRepeteableReadeCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TransactionManagerMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockRunRepeteableReadeInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TransactionManagerMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TransactionManagerMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockRunRepeteableReadeDone()
}
