// Code generated by mockery v2.53.5. DO NOT EDIT.

package mock_product_v1

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	product "route256/product/pkg/product_v1"
)

// ProductServiceClient is an autogenerated mock type for the ProductServiceClient type
type ProductServiceClient struct {
	mock.Mock
}

type ProductServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductServiceClient) EXPECT() *ProductServiceClient_Expecter {
	return &ProductServiceClient_Expecter{mock: &_m.Mock}
}

// GetProduct provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) GetProduct(ctx context.Context, in *product.GetProductRequest, opts ...grpc.CallOption) (*product.GetProductResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *product.GetProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.GetProductRequest, ...grpc.CallOption) (*product.GetProductResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *product.GetProductRequest, ...grpc.CallOption) *product.GetProductResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.GetProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *product.GetProductRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductServiceClient_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type ProductServiceClient_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - in *product.GetProductRequest
//   - opts ...grpc.CallOption
func (_e *ProductServiceClient_Expecter) GetProduct(ctx interface{}, in interface{}, opts ...interface{}) *ProductServiceClient_GetProduct_Call {
	return &ProductServiceClient_GetProduct_Call{Call: _e.mock.On("GetProduct",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ProductServiceClient_GetProduct_Call) Run(run func(ctx context.Context, in *product.GetProductRequest, opts ...grpc.CallOption)) *ProductServiceClient_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*product.GetProductRequest), variadicArgs...)
	})
	return _c
}

func (_c *ProductServiceClient_GetProduct_Call) Return(_a0 *product.GetProductResponse, _a1 error) *ProductServiceClient_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductServiceClient_GetProduct_Call) RunAndReturn(run func(context.Context, *product.GetProductRequest, ...grpc.CallOption) (*product.GetProductResponse, error)) *ProductServiceClient_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// ListSkus provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) ListSkus(ctx context.Context, in *product.ListSkusRequest, opts ...grpc.CallOption) (*product.ListSkusResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListSkus")
	}

	var r0 *product.ListSkusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.ListSkusRequest, ...grpc.CallOption) (*product.ListSkusResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *product.ListSkusRequest, ...grpc.CallOption) *product.ListSkusResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.ListSkusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *product.ListSkusRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductServiceClient_ListSkus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSkus'
type ProductServiceClient_ListSkus_Call struct {
	*mock.Call
}

// ListSkus is a helper method to define mock.On call
//   - ctx context.Context
//   - in *product.ListSkusRequest
//   - opts ...grpc.CallOption
func (_e *ProductServiceClient_Expecter) ListSkus(ctx interface{}, in interface{}, opts ...interface{}) *ProductServiceClient_ListSkus_Call {
	return &ProductServiceClient_ListSkus_Call{Call: _e.mock.On("ListSkus",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *ProductServiceClient_ListSkus_Call) Run(run func(ctx context.Context, in *product.ListSkusRequest, opts ...grpc.CallOption)) *ProductServiceClient_ListSkus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*product.ListSkusRequest), variadicArgs...)
	})
	return _c
}

func (_c *ProductServiceClient_ListSkus_Call) Return(_a0 *product.ListSkusResponse, _a1 error) *ProductServiceClient_ListSkus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductServiceClient_ListSkus_Call) RunAndReturn(run func(context.Context, *product.ListSkusRequest, ...grpc.CallOption) (*product.ListSkusResponse, error)) *ProductServiceClient_ListSkus_Call {
	_c.Call.Return(run)
	return _c
}

// NewProductServiceClient creates a new instance of ProductServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductServiceClient {
	mock := &ProductServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
