// Code generated by MockGen. DO NOT EDIT.
// Source: route256/product/pkg/product_v1 (interfaces: ProductServiceClient)

// Package mock_product_v1 is a generated GoMock package.
package mock_product_v1

import (
	context "context"
	reflect "reflect"
	product "route256/product/pkg/product_v1"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockProductServiceClient is a mock of ProductServiceClient interface.
type MockProductServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockProductServiceClientMockRecorder
}

// MockProductServiceClientMockRecorder is the mock recorder for MockProductServiceClient.
type MockProductServiceClientMockRecorder struct {
	mock *MockProductServiceClient
}

// NewMockProductServiceClient creates a new mock instance.
func NewMockProductServiceClient(ctrl *gomock.Controller) *MockProductServiceClient {
	mock := &MockProductServiceClient{ctrl: ctrl}
	mock.recorder = &MockProductServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductServiceClient) EXPECT() *MockProductServiceClientMockRecorder {
	return m.recorder
}

// GetProduct mocks base method.
func (m *MockProductServiceClient) GetProduct(arg0 context.Context, arg1 *product.GetProductRequest, arg2 ...grpc.CallOption) (*product.GetProductResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetProduct", varargs...)
	ret0, _ := ret[0].(*product.GetProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockProductServiceClientMockRecorder) GetProduct(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockProductServiceClient)(nil).GetProduct), varargs...)
}

// ListSkus mocks base method.
func (m *MockProductServiceClient) ListSkus(arg0 context.Context, arg1 *product.ListSkusRequest, arg2 ...grpc.CallOption) (*product.ListSkusResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSkus", varargs...)
	ret0, _ := ret[0].(*product.ListSkusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSkus indicates an expected call of ListSkus.
func (mr *MockProductServiceClientMockRecorder) ListSkus(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSkus", reflect.TypeOf((*MockProductServiceClient)(nil).ListSkus), varargs...)
}
