token: testtoken
services:
  loms: "localhost:50052"
  product: "route256.pavl.uk:8082"
port: "50051"
db: "postgres://user:password@localhost:6433/checkout"
productServiceRateLiming: 10
getProductPoolAmount: 5
tracesUrl: "http://jaeger:14268/api/traces"
